name: avdan
description: "Language cards"
publish_to: 'none'
version: 1.2.0+67

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  url_launcher: ^6.3.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.0
  infinite_scroll_pagination: ^4.0.0
  intersperse: ^2.0.0
  flutter_markdown: ^0.7.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  archive: ^3.6.1
  soundpool: ^2.4.1
  firebase_analytics: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
